### ISSUE TITLE
An error occurred during the training phase

### ISSUE THREAD

**Issue by QzzIsCoding** [Izecson/fairseq-editor#2]
#### What is your question?
I tried to train a model from English to Chinese, but there was a mistake in the training.
#### Code
`Traceback (most recent call last):
  File "/share/qzz/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/share/qzz/en2zh/fairseq-editor/fairseq_cli/train.py", line 286, in distributed_main
    main(args, init_distributed=True)
  File "/share/qzz/en2zh/fairseq-editor/fairseq_cli/train.py", line 96, in main
    train(args, trainer, task, epoch_itr)
  File "/share/qzz/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/share/qzz/en2zh/fairseq-editor/fairseq_cli/train.py", line 176, in train
    log_output = trainer.train_step(samples)
  File "/share/qzz/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/share/qzz/en2zh/fairseq-editor/fairseq/trainer.py", line 319, in train_step
    ignore_grad=is_dummy_batch,
  File "/share/qzz/en2zh/fairseq-editor/fairseq/tasks/translation_lev.py", line 175, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/share/qzz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/qzz/en2zh/fairseq-editor/fairseq/criterions/nat_loss.py", line 218, in forward
    factor=outputs[obj].get("factor", 1.0)
  File "/share/qzz/en2zh/fairseq-editor/fairseq/criterions/nat_loss.py", line 53, in _compute_loss
    outputs, targets = outputs[masks], targets[masks]
IndexError: The shape of the mask [56, 32] at index 1 does not match the shape of the indexed tensor [56, 33] at index 1`

#### What have you tried?
I use the parameters：
`fairseq-train \
	${data_dir}/data-bin \
	--save-dir ${model_dir}/checkpoints \
	--source-lang ${src} --target-lang ${tgt}  \
	--ddp-backend=no_c10d \
	--task translation_lev \
	--criterion nat_loss \
	--arch editor_transformer \
	--noise random_delete \
	--optimizer adam --adam-betas '(0.9,0.98)' \
	--lr 0.001 --lr-scheduler inverse_sqrt \
	--warmup-updates 2000 \
	--warmup-init-lr '1e-07' --label-smoothing 0.1 \
	--share-all-embeddings --no-share-discriminator \
	--dropout 0.3 --weight-decay 0.01 \
	--decoder-learned-pos --encoder-learned-pos \
	--apply-bert-init \
	--log-format 'simple' \
	--log-interval 5 \
	--fixed-validation-seed 7 \
	--max-tokens 2048 \
	--save-interval-updates 10000 \
	--max-update 100000`
I tried to change arch to levenshtein_transformer, and it can train normally.

#### What's your environment?
 - fairseq Version (0.9.0):
 - PyTorch Version (1.10.0)
 - OS (Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
      git clone https://github.com/pytorch/fairseq
      cd fairseq
      pip install --editable ./
      python setup.py build_ext --inplace
 - Python version: 3.7
 - CUDA/cuDNN version: 11.0

**Comment by piyusharma08** [comment]
Hi @QzzIsCoding,
Were you able to resolve this error? I am getting the same error.

**Comment by QzzIsCoding** [comment]
@piyusharma08 Hi, I didn't solve the error so far.

**Comment by weijia-xu** [comment]
Hi @QzzIsCoding,

I'm not sure if you are using CPU or GPU mode, but I can only replicate this error when training on CPU. I've fixed the issue in this update: https://github.com/Izecson/fairseq-editor/commit/0363888cd6ea866574140c04c39ccdb13bb9b4ce

If you want to train it on GPU, you'll need to compile the cuda kernel code by running ``python setup.py build_ext --inplace`` on a device with CUDA and CUDNN installed.

Also, it is recommended to use ``--noise random_delete_shuffle`` instead of ``--noise random_delete`` to train EDITOR.
